"""initial schema

Revision ID: 9d2956879ac3
Revises: 
Create Date: 2026-07-09 21:05:59.898038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d2956879ac3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('info', 'warning', 'success', 'danger', name='logtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.Enum('student', 'admin', name='userrole'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('student_id', sa.String(length=64), nullable=True),
    sa.Column('college', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('active_session_token', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('exams',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('passing_marks', sa.Integer(), nullable=False),
    sa.Column('negative_marking', sa.Boolean(), nullable=False),
    sa.Column('random_question_order', sa.Boolean(), nullable=False),
    sa.Column('random_option_order', sa.Boolean(), nullable=False),
    sa.Column('max_active_students', sa.Integer(), nullable=False),
    sa.Column('queue_capacity', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('programming_languages', sa.JSON(), nullable=False),
    sa.Column('browser_restrictions', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'unpublished', 'archived', name='examstatus'), nullable=False),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exams_slug'), 'exams', ['slug'], unique=True)
    op.create_index(op.f('ix_exams_status'), 'exams', ['status'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('type', sa.Enum('mcq', 'multiple_correct', 'coding', 'sql', 'fill_blank', 'short_answer', 'descriptive', name='questiontype'), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('correct_answer', sa.JSON(), nullable=False),
    sa.Column('initial_code', sa.Text(), nullable=True),
    sa.Column('test_cases', sa.JSON(), nullable=False),
    sa.Column('difficulty', sa.String(length=32), nullable=False),
    sa.Column('marks', sa.Integer(), nullable=False),
    sa.Column('negative_marks', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=True),
    sa.Column('topic', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=1024), nullable=True),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('programming_language', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_type'), 'questions', ['type'], unique=False)
    op.create_table('activity_log',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('student_id', sa.String(length=32), nullable=True),
    sa.Column('exam_id', sa.String(length=32), nullable=True),
    sa.Column('session_id', sa.String(length=32), nullable=True),
    sa.Column('event_type', sa.Enum('opened_link', 'login', 'start_exam_click', 'queue_entry', 'queue_exit', 'exam_start', 'submission', 'logout', 'browser_refresh', 'disconnect', 'reconnect', name='activityeventtype'), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('device', sa.String(length=255), nullable=True),
    sa.Column('browser', sa.String(length=255), nullable=True),
    sa.Column('event_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_activity_log_created_at'), 'activity_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_activity_log_event_type'), 'activity_log', ['event_type'], unique=False)
    op.create_index(op.f('ix_activity_log_exam_id'), 'activity_log', ['exam_id'], unique=False)
    op.create_index(op.f('ix_activity_log_student_id'), 'activity_log', ['student_id'], unique=False)
    op.create_table('exam_questions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('exam_id', sa.String(length=32), nullable=False),
    sa.Column('question_id', sa.String(length=32), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exam_id', 'question_id', name='uq_exam_question')
    )
    op.create_index(op.f('ix_exam_questions_exam_id'), 'exam_questions', ['exam_id'], unique=False)
    op.create_table('exam_sessions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('exam_id', sa.String(length=32), nullable=False),
    sa.Column('student_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('waiting', 'in_progress', 'submitted', 'exited', name='sessionstatus'), nullable=False),
    sa.Column('queue_position', sa.Integer(), nullable=False),
    sa.Column('joined_queue_at', sa.DateTime(), nullable=True),
    sa.Column('entered_exam_at', sa.DateTime(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('time_remaining_seconds', sa.Integer(), nullable=False),
    sa.Column('proctoring_violations', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('total_marks', sa.Integer(), nullable=True),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('device', sa.String(length=255), nullable=True),
    sa.Column('browser', sa.String(length=255), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_sessions_exam_id'), 'exam_sessions', ['exam_id'], unique=False)
    op.create_index(op.f('ix_exam_sessions_status'), 'exam_sessions', ['status'], unique=False)
    op.create_index(op.f('ix_exam_sessions_student_id'), 'exam_sessions', ['student_id'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('session_id', sa.String(length=32), nullable=False),
    sa.Column('question_id', sa.String(length=32), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('marks_awarded', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['exam_sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'question_id', name='uq_session_question')
    )
    op.create_index(op.f('ix_answers_session_id'), 'answers', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answers_session_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_exam_sessions_student_id'), table_name='exam_sessions')
    op.drop_index(op.f('ix_exam_sessions_status'), table_name='exam_sessions')
    op.drop_index(op.f('ix_exam_sessions_exam_id'), table_name='exam_sessions')
    op.drop_table('exam_sessions')
    op.drop_index(op.f('ix_exam_questions_exam_id'), table_name='exam_questions')
    op.drop_table('exam_questions')
    op.drop_index(op.f('ix_activity_log_student_id'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_exam_id'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_event_type'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_created_at'), table_name='activity_log')
    op.drop_table('activity_log')
    op.drop_index(op.f('ix_questions_type'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_exams_status'), table_name='exams')
    op.drop_index(op.f('ix_exams_slug'), table_name='exams')
    op.drop_table('exams')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
